# ./docker-compose.yml
version: '3.3'

networks:
    ibot:
      external: false
    ibot-proxy:
      external:
        name: nginx_proxy

services:
  bot:
    build: .
    container_name: incidentBot-discord
    environment:
      - FS_PASSCODE_PORT
      - FS_SECRET
      - FS_ARCHIVE_DIRECTORY
      - ARCHIVE_CONTAINER=web
      - MONGO_CONN
      - MONGO_PORT
      - MONGO_ROOT_USER
      - MONGO_ROOT_PASS
    volumes:
      - ./:/code
      - $LOCAL_ARCHIVE_DIRECTORY/:$FS_ARCHIVE_DIRECTORY
    stdin_open: true
    tty: true
    restart: always
    networks:
      - ibot

  mongo:
    image: mongo
    container_name: incidentBot-mongo
    restart: always
    volumes:
        - ./data/db:/data/db
    expose:
        - 27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    networks:
      - ibot

  mongo-express:
    image: mongo-express
    container_name: incidentBot-mongoexpress
    restart: always
    ports:
        - 40003:8081
    environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
    networks:
        - ibot

  web:
    build: ./wolfpack-file-server
    expose:
      - $FS_ARCHIVE_PORT
      - $FS_PASSCODE_PORT
    volumes:
      - $LOCAL_ARCHIVE_DIRECTORY/:$FS_ARCHIVE_DIRECTORY
      - $LOCAL_LOG_DIRECTORY:$FS_LOG_DIRECTORY
    environment:
      - FS_LOG_DIRECTORY
      - FS_ARCHIVE_DIRECTORY
      - FS_PASSCODE_PORT
      - FS_ARCHIVE_PORT
      - FS_SECRET
      - FS_HOST
      - FS_FRONTEND_PORT
      - LETSENCRYPT_EMAIL=it@cj-mayer.de
      - LETSENCRYPT_HOST=api.wpr.cj-mayer.de
      - VIRTUAL_HOST=api.wpr.cj-mayer.de
      - VIRTUAL_PORT=$FS_ARCHIVE_PORT

    networks:
      - ibot

  frontend:
    build: ./wolfpack-file-server/file-server-frontend
    depends_on:
      - web
    environment:
      LETSENCRYPT_EMAIL: it@cj-mayer.de
      LETSENCRYPT_HOST: wpr.cj-mayerde
      VIRTUAL_HOST: wpr.cj-mayer.de
      VIRTUAL_PORT: 5000
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - ibot
      - ibot-proxy
